//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Account root</summary>
	[PublishedModel("accountRoot")]
	public partial class AccountRoot : PublishedContentModel, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "accountRoot";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AccountRoot, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public AccountRoot(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Age Group Required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("ageGroupRequired")]
		public string AgeGroupRequired => this.Value<string>("ageGroupRequired");

		///<summary>
		/// Age Group Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("ageGroupTitle")]
		public string AgeGroupTitle => this.Value<string>("ageGroupTitle");

		///<summary>
		/// Cancel Button Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cancelButtonTitle")]
		public string CancelButtonTitle => this.Value<string>("cancelButtonTitle");

		///<summary>
		/// Change Password Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("changePasswordText")]
		public string ChangePasswordText => this.Value<string>("changePasswordText");

		///<summary>
		/// Communication - Mail Required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("communicationMailRequired")]
		public string CommunicationMailRequired => this.Value<string>("communicationMailRequired");

		///<summary>
		/// Communication - Phone Required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("communicationPhoneRequired")]
		public string CommunicationPhoneRequired => this.Value<string>("communicationPhoneRequired");

		///<summary>
		/// Communication - WhatsApp Required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("communicationWhatsAppRequired")]
		public string CommunicationWhatsAppRequired => this.Value<string>("communicationWhatsAppRequired");

		///<summary>
		/// Edit Consent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("editConsent")]
		public string EditConsent => this.Value<string>("editConsent");

		///<summary>
		/// Email Communication Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("emailCommunicationTitle")]
		public string EmailCommunicationTitle => this.Value<string>("emailCommunicationTitle");

		///<summary>
		/// Email Format
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("emailFormat")]
		public string EmailFormat => this.Value<string>("emailFormat");

		///<summary>
		/// Email Required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("emailRequired")]
		public string EmailRequired => this.Value<string>("emailRequired");

		///<summary>
		/// Email Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("emailTitle")]
		public string EmailTitle => this.Value<string>("emailTitle");

		///<summary>
		/// HPiD Redirection Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("hPiDRedirectionText")]
		public string HPiDredirectionText => this.Value<string>("hPiDRedirectionText");

		///<summary>
		/// Last Date Payment Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("lastDatePaymentTitle")]
		public string LastDatePaymentTitle => this.Value<string>("lastDatePaymentTitle");

		///<summary>
		/// My Account Navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("myAccountNavigation")]
		public IEnumerable<ContentMenuElement> MyAccountNavigation => this.Value<IEnumerable<ContentMenuElement>>("myAccountNavigation");

		///<summary>
		/// Name Required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("nameRequired")]
		public string NameRequired => this.Value<string>("nameRequired");

		///<summary>
		/// Name Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("nameTitle")]
		public string NameTitle => this.Value<string>("nameTitle");

		///<summary>
		/// Next Date Payment Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("nextDatePaymentTitle")]
		public string NextDatePaymentTitle => this.Value<string>("nextDatePaymentTitle");

		///<summary>
		/// No Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("noTitle")]
		public string NoTitle => this.Value<string>("noTitle");

		///<summary>
		/// Phone Communication Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("phoneCommunicationTitle")]
		public string PhoneCommunicationTitle => this.Value<string>("phoneCommunicationTitle");

		///<summary>
		/// Plan Name Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("planNameTitle")]
		public string PlanNameTitle => this.Value<string>("planNameTitle");

		///<summary>
		/// Referral Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("referralCode")]
		public string ReferralCode => this.Value<string>("referralCode");

		///<summary>
		/// Save Button Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("saveButtonTitle")]
		public string SaveButtonTitle => this.Value<string>("saveButtonTitle");

		///<summary>
		/// Share Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("shareItems")]
		public IEnumerable<IPublishedContent> ShareItems => this.Value<IEnumerable<IPublishedContent>>("shareItems");

		///<summary>
		/// Subscription Status Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("subscriptionStatusTitle")]
		public string SubscriptionStatusTitle => this.Value<string>("subscriptionStatusTitle");

		///<summary>
		/// Title of Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("titleOfPage")]
		public string TitleOfPage => this.Value<string>("titleOfPage");

		///<summary>
		/// Title of Page Edit
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("titleOfPageEdit")]
		public string TitleOfPageEdit => this.Value<string>("titleOfPageEdit");

		///<summary>
		/// Unique Id
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("uniqueId")]
		public string UniqueId => this.Value<string>("uniqueId");

		///<summary>
		/// WhatsApp Communication Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("whatsAppCommunicationTitle")]
		public string WhatsAppCommunicationTitle => this.Value<string>("whatsAppCommunicationTitle");

		///<summary>
		/// WhatsApp Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("whatsAppTitle")]
		public string WhatsAppTitle => this.Value<string>("whatsAppTitle");

		///<summary>
		/// WhatsApp Validation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("whatsAppValidation")]
		public string WhatsAppValidation => this.Value<string>("whatsAppValidation");

		///<summary>
		/// Yes Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("yesTitle")]
		public string YesTitle => this.Value<string>("yesTitle");

		///<summary>
		/// HeadSectionScripts: HeadSectionScripts - *Not Mandatory. The Page Specific code inside the head section goes here:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("headSectionScripts")]
		public string HeadSectionScripts => SEO.GetHeadSectionScripts(this);

		///<summary>
		/// Meta Description: SEO Meta Description :
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => SEO.GetMetaDescription(this);

		///<summary>
		/// Meta keywords: Meta Keywords:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("metaKeywords")]
		public IEnumerable<string> MetaKeywords => SEO.GetMetaKeywords(this);

		///<summary>
		/// Meta Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("metaName")]
		public string MetaName => SEO.GetMetaName(this);

		///<summary>
		/// Page Title: Browser Title - title shown in the Browser window / tab, and most important on search-engine listings.:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageName")]
		public string PageName => SEO.GetPageName(this);

		///<summary>
		/// SEO Can Index: If checked means SEO can track this page, In case of unchecked SEO can not track.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("sEOCanIndex")]
		public bool SEocanIndex => SEO.GetSEocanIndex(this);

		///<summary>
		/// SEO Follow links: SEO Follow links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("sEOFollowLinks")]
		public bool SEofollowLinks => SEO.GetSEofollowLinks(this);
	}
}
