//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>BannerElement</summary>
	[PublishedModel("bannerElement")]
	public partial class BannerElement : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "bannerElement";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BannerElement, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public BannerElement(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Activated
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("activated")]
		public bool Activated => this.Value<bool>("activated");

		///<summary>
		/// Banner Allow for Guest User
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bannerAllowForGuestUser")]
		public bool BannerAllowForGuestUser => this.Value<bool>("bannerAllowForGuestUser");

		///<summary>
		/// Banner Allow for Login User
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bannerAllowForLoginUser")]
		public bool BannerAllowForLoginUser => this.Value<bool>("bannerAllowForLoginUser");

		///<summary>
		/// Banner URL: Banner URL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bannerURL")]
		public Umbraco.Web.Models.Link BannerUrl => this.Value<Umbraco.Web.Models.Link>("bannerURL");

		///<summary>
		/// Button 1 design: Button 1 design
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("button1Design")]
		public string Button1Design => this.Value<string>("button1Design");

		///<summary>
		/// Button 1 Url: Button 1 Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("button1Url")]
		public Umbraco.Web.Models.Link Button1Url => this.Value<Umbraco.Web.Models.Link>("button1Url");

		///<summary>
		/// Button 2 design: Button 2 design
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("button2Design")]
		public string Button2Design => this.Value<string>("button2Design");

		///<summary>
		/// Button 2 Url: Button 2 Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("button2Url")]
		public Umbraco.Web.Models.Link Button2Url => this.Value<Umbraco.Web.Models.Link>("button2Url");

		///<summary>
		/// Button (If Any) - Max 2 (Applied for only image banner section): Button (If Any) - Max 2 (Applied for only image banner section)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("buttonIfAnyMax2AppliedForOnlyImageBannerSection")]
		public string ButtonIfAnyMax2AppliedForOnlyImageBannerSection => this.Value<string>("buttonIfAnyMax2AppliedForOnlyImageBannerSection");

		///<summary>
		/// Button (If Any) - Max 2 (Applied forTracking banner section)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("buttonIfAnyMax2AppliedForTrackingBannerSection")]
		public string ButtonIfAnyMax2AppliedForTrackingBannerSection => this.Value<string>("buttonIfAnyMax2AppliedForTrackingBannerSection");

		///<summary>
		/// Desktop image: Desktop image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("desktopImage")]
		public IPublishedContent DesktopImage => this.Value<IPublishedContent>("desktopImage");

		///<summary>
		/// Desktop next-gen image: Upload here WEBP image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("desktopNextGenImage")]
		public IPublishedContent DesktopNextGenImage => this.Value<IPublishedContent>("desktopNextGenImage");

		///<summary>
		/// Disclaimer: If you not selected any then this banner  will appear for both
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("disclaimer")]
		public string Disclaimer => this.Value<string>("disclaimer");

		///<summary>
		/// Heading: Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("heading")]
		public string Heading => this.Value<string>("heading");

		///<summary>
		/// Image Section: Image Section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("imageSection")]
		public string ImageSection => this.Value<string>("imageSection");

		///<summary>
		/// IsCouponBundleBanner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isCouponBundleBanner")]
		public bool IsCouponBundleBanner => this.Value<bool>("isCouponBundleBanner");

		///<summary>
		/// Is Enable Tracker
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isEnableTracker")]
		public bool IsEnableTracker => this.Value<bool>("isEnableTracker");

		///<summary>
		/// isVideo: isVideo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isVideo")]
		public string IsVideo => this.Value<string>("isVideo");

		///<summary>
		/// Is Wonk Banner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isWonkBanner")]
		public bool IsWonkBanner => this.Value<bool>("isWonkBanner");

		///<summary>
		/// Mobile image: Mobile image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("mobileImage")]
		public IPublishedContent MobileImage => this.Value<IPublishedContent>("mobileImage");

		///<summary>
		/// Mobile next-gen image: Upload here WEBP image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("mobileNextGenImage")]
		public IPublishedContent MobileNextGenImage => this.Value<IPublishedContent>("mobileNextGenImage");

		///<summary>
		/// MP4 File: MP4 File
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("mP4File")]
		public IPublishedContent MP4File => this.Value<IPublishedContent>("mP4File");

		///<summary>
		/// Page to display Banner: If you not mention any page then this banner will display on all pages
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageToDisplayBanner")]
		public IEnumerable<Umbraco.Web.Models.Link> PageToDisplayBanner => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("pageToDisplayBanner");

		///<summary>
		/// Paragraph (If Any): Paragraph (If Any)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("paragraphIfAny")]
		public string ParagraphIfAny => this.Value<string>("paragraphIfAny");

		///<summary>
		/// Sub heading: Sub heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("subHeading")]
		public string SubHeading => this.Value<string>("subHeading");

		///<summary>
		/// Allow for Subscription: Pick subscription from Subscription list
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("subscriptionType")]
		public IEnumerable<Umbraco.Web.Models.Link> SubscriptionType => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("subscriptionType");

		///<summary>
		/// Sub Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("subTitle")]
		public string SubTitle => this.Value<string>("subTitle");

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("title")]
		public string Title => this.Value<string>("title");

		///<summary>
		/// Video desktop image: Video desktop image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("videoDesktopImage")]
		public IPublishedContent VideoDesktopImage => this.Value<IPublishedContent>("videoDesktopImage");

		///<summary>
		/// Video desktop next-gen image: Upload here WEBP image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("videoDesktopNextGenImage")]
		public IPublishedContent VideoDesktopNextGenImage => this.Value<IPublishedContent>("videoDesktopNextGenImage");

		///<summary>
		/// Video icon (If Any): Video icon (If Any)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("videoIconIfAny")]
		public IPublishedContent VideoIconIfAny => this.Value<IPublishedContent>("videoIconIfAny");

		///<summary>
		/// Video mobile image: Video mobile image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("videoMobileImage")]
		public IPublishedContent VideoMobileImage => this.Value<IPublishedContent>("videoMobileImage");

		///<summary>
		/// Video mobile next-gen image: Upload here WEBP image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("videoMobileNextGenImage")]
		public IPublishedContent VideoMobileNextGenImage => this.Value<IPublishedContent>("videoMobileNextGenImage");

		///<summary>
		/// Video Section: videoSection
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("videoSection")]
		public string VideoSection => this.Value<string>("videoSection");

		///<summary>
		/// Video type: Video type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("videoType")]
		public string VideoType => this.Value<string>("videoType");

		///<summary>
		/// Wonk Banner Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("wonkBannerMessage")]
		public string WonkBannerMessage => this.Value<string>("wonkBannerMessage");

		///<summary>
		/// Wonk URL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("wonkURL")]
		public string WonkUrl => this.Value<string>("wonkURL");

		///<summary>
		/// Youtube Id: Youtube Id
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("youtubeId")]
		public string YoutubeId => this.Value<string>("youtubeId");
	}
}
