//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Header</summary>
	[PublishedModel("header")]
	public partial class Header : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "header";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Header, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Header(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// AboutUs
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("aboutUs")]
		public Umbraco.Web.Models.Link AboutUs => this.Value<Umbraco.Web.Models.Link>("aboutUs");

		///<summary>
		/// After Logged In Menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("afterLoggedInMenu")]
		public IEnumerable<SubscriptionWiseDocument> AfterLoggedInMenu => this.Value<IEnumerable<SubscriptionWiseDocument>>("afterLoggedInMenu");

		///<summary>
		/// Contact Us
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("contactUs")]
		public Umbraco.Web.Models.Link ContactUs => this.Value<Umbraco.Web.Models.Link>("contactUs");

		///<summary>
		/// Display Subscription Message on Header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("displaySubscriptionMessageOnHeader")]
		public IEnumerable<Umbraco.Web.Models.Link> DisplaySubscriptionMessageOnHeader => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("displaySubscriptionMessageOnHeader");

		///<summary>
		/// FAQs
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("fAQs")]
		public Umbraco.Web.Models.Link FAqs => this.Value<Umbraco.Web.Models.Link>("fAQs");

		///<summary>
		/// Global Icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("globalIcon")]
		public IPublishedContent GlobalIcon => this.Value<IPublishedContent>("globalIcon");

		///<summary>
		/// Help Center
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("helpCenter")]
		public string HelpCenter => this.Value<string>("helpCenter");

		///<summary>
		/// HP Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("hPLogo")]
		public IPublishedContent HPlogo => this.Value<IPublishedContent>("hPLogo");

		///<summary>
		/// Language Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("languageName")]
		public IEnumerable<LanguageElement> LanguageName => this.Value<IEnumerable<LanguageElement>>("languageName");

		///<summary>
		/// Language not display on
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("languageNotDisplayOn")]
		public IEnumerable<Umbraco.Web.Models.Link> LanguageNotDisplayOn => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("languageNotDisplayOn");

		///<summary>
		/// PLC Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("logo")]
		public IPublishedContent Logo => this.Value<IPublishedContent>("logo");

		///<summary>
		/// Manage Your Subscription: this will display post login
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("manageYourSubscription")]
		public string ManageYourSubscription => this.Value<string>("manageYourSubscription");

		///<summary>
		/// Pricing Tab
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pricingTab")]
		public Umbraco.Web.Models.Link PricingTab => this.Value<Umbraco.Web.Models.Link>("pricingTab");

		///<summary>
		/// Sign In
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("signIn")]
		public Umbraco.Web.Models.Link SignIn => this.Value<Umbraco.Web.Models.Link>("signIn");

		///<summary>
		/// Sign Out
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("signOut")]
		public Umbraco.Web.Models.Link SignOut => this.Value<Umbraco.Web.Models.Link>("signOut");

		///<summary>
		/// Start your Subscription: this will display before login
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("startYourSubscription")]
		public string StartYourSubscription => this.Value<string>("startYourSubscription");

		///<summary>
		/// TopBand Webinar Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("topBandWebinarTitle")]
		public string TopBandWebinarTitle => this.Value<string>("topBandWebinarTitle");

		///<summary>
		/// Your subscription has ended
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("yourSubscriptionHasEnded")]
		public string YourSubscriptionHasEnded => this.Value<string>("yourSubscriptionHasEnded");
	}
}
