//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Subscription Mailer</summary>
	[PublishedModel("subscriptionMailer")]
	public partial class SubscriptionMailer : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "subscriptionMailer";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SubscriptionMailer, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public SubscriptionMailer(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Age Group: If You select age group then "Body with Video" content share on mail.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("ageGroup")]
		public IEnumerable<Umbraco.Web.Models.Link> AgeGroup => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("ageGroup");

		///<summary>
		/// Body
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("body")]
		public IHtmlString Body => this.Value<IHtmlString>("body");

		///<summary>
		/// Body With Videos
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bodyWithVideos")]
		public IHtmlString BodyWithVideos => this.Value<IHtmlString>("bodyWithVideos");

		///<summary>
		/// Footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("footer")]
		public IHtmlString Footer => this.Value<IHtmlString>("footer");

		///<summary>
		/// Free Worksheet Attachment
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("freeWorksheetAttachment")]
		public Umbraco.Web.Models.Link FreeWorksheetAttachment => this.Value<Umbraco.Web.Models.Link>("freeWorksheetAttachment");

		///<summary>
		/// Header Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("headerLogo")]
		public IPublishedContent HeaderLogo => this.Value<IPublishedContent>("headerLogo");

		///<summary>
		/// Header Logo Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("headerLogoUrl")]
		public string HeaderLogoUrl => this.Value<string>("headerLogoUrl");

		///<summary>
		/// Mail BCC
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("mailBCC")]
		public IEnumerable<string> MailBcc => this.Value<IEnumerable<string>>("mailBCC");

		///<summary>
		/// Mail CC
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("mailCC")]
		public IEnumerable<string> MailCC => this.Value<IEnumerable<string>>("mailCC");

		///<summary>
		/// Ranking
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("ranking")]
		public string Ranking => this.Value<string>("ranking");

		///<summary>
		/// Social Share
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("socialShare")]
		public IHtmlString SocialShare => this.Value<IHtmlString>("socialShare");

		///<summary>
		/// Subject
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("subject")]
		public string Subject => this.Value<string>("subject");

		///<summary>
		/// Visit Print Learn Center
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("visitPrintLearnCenter")]
		public IPublishedContent VisitPrintLearnCenter => this.Value<IPublishedContent>("visitPrintLearnCenter");

		///<summary>
		/// Visit Print Learn Center Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("visitPrintLearnCenterUrl")]
		public string VisitPrintLearnCenterUrl => this.Value<string>("visitPrintLearnCenterUrl");
	}
}
