//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Worksheet Item</summary>
	[PublishedModel("worksheetRoot")]
	public partial class WorksheetRoot : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "worksheetRoot";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<WorksheetRoot, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public WorksheetRoot(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Select Class: Age Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("ageTitle")]
		public Umbraco.Web.Models.Link AgeTitle => this.Value<Umbraco.Web.Models.Link>("ageTitle");

		///<summary>
		/// Bitly link: Bitly link you can enter here otherwise when page load then automatically generate and update in CMS.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bitlyLink")]
		public string BitlyLink => this.Value<string>("bitlyLink");

		///<summary>
		/// Button Text: Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("buttonText")]
		public string ButtonText => this.Value<string>("buttonText");

		///<summary>
		/// CBSE Content Included
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cBSEContentIncluded")]
		public bool CBsecontentIncluded => this.Value<bool>("cBSEContentIncluded");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("description")]
		public IHtmlString Description => this.Value<IHtmlString>("description");

		///<summary>
		/// Document and Subscriptions
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("documentAndSubscriptions")]
		public IEnumerable<SubscriptionWiseDocument> DocumentAndSubscriptions => this.Value<IEnumerable<SubscriptionWiseDocument>>("documentAndSubscriptions");

		///<summary>
		/// Facebook Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("facebookContent")]
		public string FacebookContent => this.Value<string>("facebookContent");

		///<summary>
		/// Is Active
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isActive")]
		public bool IsActive => this.Value<bool>("isActive");

		///<summary>
		/// Is Guest User Sheet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isGuestUserSheet")]
		public bool IsGuestUserSheet => this.Value<bool>("isGuestUserSheet");

		///<summary>
		/// Is Quiz Worksheet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isQuizWorksheet")]
		public bool IsQuizWorksheet => this.Value<bool>("isQuizWorksheet");

		///<summary>
		/// Is Subscription Wise Document
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("isSubscriptionWiseDocument")]
		public bool IsSubscriptionWiseDocument => this.Value<bool>("isSubscriptionWiseDocument");

		///<summary>
		/// Mail Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("mailContent")]
		public string MailContent => this.Value<string>("mailContent");

		///<summary>
		/// Max. Age
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("maxAge")]
		public int MaxAge => this.Value<int>("maxAge");

		///<summary>
		/// Min. Age
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("minAge")]
		public int MinAge => this.Value<int>("minAge");

		///<summary>
		/// Mobile Next-Gen Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("mobileNextGenImage")]
		public IPublishedContent MobileNextGenImage => this.Value<IPublishedContent>("mobileNextGenImage");

		///<summary>
		/// Next-Gen Image: Upload here WEBP image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("nextGenImage")]
		public IPublishedContent NextGenImage => this.Value<IPublishedContent>("nextGenImage");

		///<summary>
		/// Select Subject
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("selectSubject")]
		public Umbraco.Web.Models.Link SelectSubject => this.Value<Umbraco.Web.Models.Link>("selectSubject");

		///<summary>
		/// Select Week
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("selectWeek")]
		public Umbraco.Web.Models.Link SelectWeek => this.Value<Umbraco.Web.Models.Link>("selectWeek");

		///<summary>
		/// Share Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("shareContent")]
		public string ShareContent => this.Value<string>("shareContent");

		///<summary>
		/// Sharing Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("sharingText")]
		public string SharingText => this.Value<string>("sharingText");

		///<summary>
		/// Subscription: Please navigate from Subscription-SubscriptionList folder
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("subscription")]
		public IEnumerable<Umbraco.Web.Models.Link> Subscription => this.Value<IEnumerable<Umbraco.Web.Models.Link>>("subscription");

		///<summary>
		/// Sub Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("subTitle")]
		public string SubTitle => this.Value<string>("subTitle");

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("title")]
		public string Title => this.Value<string>("title");

		///<summary>
		/// Select Topic
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("Topic")]
		public Umbraco.Web.Models.Link Topic => this.Value<Umbraco.Web.Models.Link>("Topic");

		///<summary>
		/// Upgrade Button: Upgrade Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("upgradeButton")]
		public Umbraco.Web.Models.Link UpgradeButton => this.Value<Umbraco.Web.Models.Link>("upgradeButton");

		///<summary>
		/// Upload Mobile Thumbnail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("uploadMobileThumbnail")]
		public IPublishedContent UploadMobileThumbnail => this.Value<IPublishedContent>("uploadMobileThumbnail");

		///<summary>
		/// Upload PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("uploadPDF")]
		public string UploadPdf => this.Value<string>("uploadPDF");

		///<summary>
		/// Upload Preview PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("uploadPreviewPDF")]
		public string UploadPreviewPdf => this.Value<string>("uploadPreviewPDF");

		///<summary>
		/// Upload Thumbnail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("uploadThumbnail")]
		public IPublishedContent UploadThumbnail => this.Value<IPublishedContent>("uploadThumbnail");

		///<summary>
		/// Use Share Content from here: If checked then content share from here
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("useShareContentFromHere")]
		public bool UseShareContentFromHere => this.Value<bool>("useShareContentFromHere");

		///<summary>
		/// Volume Backgroung CSS: Volume Backgroung CSS
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("volumeBackgroungCSS")]
		public string VolumeBackgroungCss => this.Value<string>("volumeBackgroungCSS");

		///<summary>
		/// WhatsApp Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("whatsAppContent")]
		public string WhatsAppContent => this.Value<string>("whatsAppContent");
	}
}
