//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.12.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Bonus Add Subscriptions</summary>
	[PublishedModel("bonusAddSubscriptions")]
	public partial class BonusAddSubscriptions : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const string ModelTypeAlias = "bonusAddSubscriptions";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BonusAddSubscriptions, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public BonusAddSubscriptions(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Activated On Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("activatedOnTitle")]
		public string ActivatedOnTitle => this.Value<string>("activatedOnTitle");

		///<summary>
		/// Age Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("ageTitle")]
		public string AgeTitle => this.Value<string>("ageTitle");

		///<summary>
		/// Buy Now Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("buyNowButton")]
		public global::Umbraco.Web.Models.Link BuyNowButton => this.Value<global::Umbraco.Web.Models.Link>("buyNowButton");

		///<summary>
		/// Days Remaining Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("daysRemainingTitle")]
		public string DaysRemainingTitle => this.Value<string>("daysRemainingTitle");

		///<summary>
		/// Days Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("daysTitle")]
		public string DaysTitle => this.Value<string>("daysTitle");

		///<summary>
		/// Duration Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("durationTitle")]
		public string DurationTitle => this.Value<string>("durationTitle");

		///<summary>
		/// Ends On Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("endsOnTitle")]
		public string EndsOnTitle => this.Value<string>("endsOnTitle");

		///<summary>
		/// Is Active
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("isActive")]
		public bool IsActive => this.Value<bool>("isActive");

		///<summary>
		/// Is Recommended
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("isRecommended")]
		public bool IsRecommended => this.Value<bool>("isRecommended");

		///<summary>
		/// No Limit Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("noLimitTitle")]
		public string NoLimitTitle => this.Value<string>("noLimitTitle");

		///<summary>
		/// Plan Punch Line
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("planPunchLine")]
		public string PlanPunchLine => this.Value<string>("planPunchLine");

		///<summary>
		/// Plan Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("planTitle")]
		public string PlanTitle => this.Value<string>("planTitle");

		///<summary>
		/// Ranking
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("ranking")]
		public string Ranking => this.Value<string>("ranking");

		///<summary>
		/// Recommended Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("recommendedTitle")]
		public string RecommendedTitle => this.Value<string>("recommendedTitle");

		///<summary>
		/// Renew Now Button Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("renewNowButtonTitle")]
		public string RenewNowButtonTitle => this.Value<string>("renewNowButtonTitle");

		///<summary>
		/// Standard Selection
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("standardSelection")]
		public global::Umbraco.Web.Models.Link StandardSelection => this.Value<global::Umbraco.Web.Models.Link>("standardSelection");

		///<summary>
		/// Subscription Availed Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subscriptionAvailedText")]
		public string SubscriptionAvailedText => this.Value<string>("subscriptionAvailedText");

		///<summary>
		/// Subscription Benefits
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subscriptionBenefits")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.SubscriptionBenefits> SubscriptionBenefits => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.SubscriptionBenefits>>("subscriptionBenefits");

		///<summary>
		/// Subscription Details
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subscriptionDetails")]
		public global::System.Collections.Generic.IEnumerable<string> SubscriptionDetails => this.Value<global::System.Collections.Generic.IEnumerable<string>>("subscriptionDetails");

		///<summary>
		/// Subscription Details Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subscriptionDetailsTitle")]
		public string SubscriptionDetailsTitle => this.Value<string>("subscriptionDetailsTitle");

		///<summary>
		/// Subscription Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subscriptionName")]
		public global::Umbraco.Web.Models.Link SubscriptionName => this.Value<global::Umbraco.Web.Models.Link>("subscriptionName");

		///<summary>
		/// Subscription Plan Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subscriptionPlanName")]
		public string SubscriptionPlanName => this.Value<string>("subscriptionPlanName");

		///<summary>
		/// Subscription Plan Name Icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subscriptionPlanNameIcon")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent SubscriptionPlanNameIcon => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("subscriptionPlanNameIcon");

		///<summary>
		/// Upgrade Now Button Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("upgradeNowButtonTitle")]
		public string UpgradeNowButtonTitle => this.Value<string>("upgradeNowButtonTitle");

		///<summary>
		/// Validation Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("validationText")]
		public string ValidationText => this.Value<string>("validationText");

		///<summary>
		/// Years Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("yearsTitle")]
		public string YearsTitle => this.Value<string>("yearsTitle");
	}
}
