//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.12.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Subscription Mailer</summary>
	[PublishedModel("subscriptionMailer")]
	public partial class SubscriptionMailer : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const string ModelTypeAlias = "subscriptionMailer";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SubscriptionMailer, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public SubscriptionMailer(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Age Group: If You select age group then "Body with Video" content share on mail.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("ageGroup")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> AgeGroup => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link>>("ageGroup");

		///<summary>
		/// Body
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("body")]
		public global::System.Web.IHtmlString Body => this.Value<global::System.Web.IHtmlString>("body");

		///<summary>
		/// Body With Videos
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("bodyWithVideos")]
		public global::System.Web.IHtmlString BodyWithVideos => this.Value<global::System.Web.IHtmlString>("bodyWithVideos");

		///<summary>
		/// Footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("footer")]
		public global::System.Web.IHtmlString Footer => this.Value<global::System.Web.IHtmlString>("footer");

		///<summary>
		/// Free Worksheet Attachment
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("freeWorksheetAttachment")]
		public global::Umbraco.Web.Models.Link FreeWorksheetAttachment => this.Value<global::Umbraco.Web.Models.Link>("freeWorksheetAttachment");

		///<summary>
		/// Header Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("headerLogo")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent HeaderLogo => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("headerLogo");

		///<summary>
		/// Header Logo Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("headerLogoUrl")]
		public string HeaderLogoUrl => this.Value<string>("headerLogoUrl");

		///<summary>
		/// Mail BCC
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("mailBCC")]
		public global::System.Collections.Generic.IEnumerable<string> MailBcc => this.Value<global::System.Collections.Generic.IEnumerable<string>>("mailBCC");

		///<summary>
		/// Mail CC
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("mailCC")]
		public global::System.Collections.Generic.IEnumerable<string> MailCC => this.Value<global::System.Collections.Generic.IEnumerable<string>>("mailCC");

		///<summary>
		/// Ranking
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("ranking")]
		public string Ranking => this.Value<string>("ranking");

		///<summary>
		/// Social Share
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("socialShare")]
		public global::System.Web.IHtmlString SocialShare => this.Value<global::System.Web.IHtmlString>("socialShare");

		///<summary>
		/// Subject
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subject")]
		public string Subject => this.Value<string>("subject");

		///<summary>
		/// Visit Print Learn Center
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("visitPrintLearnCenter")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent VisitPrintLearnCenter => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("visitPrintLearnCenter");

		///<summary>
		/// Visit Print Learn Center Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("visitPrintLearnCenterUrl")]
		public string VisitPrintLearnCenterUrl => this.Value<string>("visitPrintLearnCenterUrl");
	}
}
