//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.12.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Worksheet Item</summary>
	[PublishedModel("worksheetRoot")]
	public partial class WorksheetRoot : PublishedContentModel, IFooterContent, IFooterFaqs, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const string ModelTypeAlias = "worksheetRoot";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<WorksheetRoot, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public WorksheetRoot(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Select Class: Age Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("ageTitle")]
		public global::Umbraco.Web.Models.Link AgeTitle => this.Value<global::Umbraco.Web.Models.Link>("ageTitle");

		///<summary>
		/// Bitly link: Bitly link you can enter here otherwise when page load then automatically generate and update in CMS.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("bitlyLink")]
		public string BitlyLink => this.Value<string>("bitlyLink");

		///<summary>
		/// Button Text: Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("buttonText")]
		public string ButtonText => this.Value<string>("buttonText");

		///<summary>
		/// CBSE Content Included
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("cBSEContentIncluded")]
		public bool CBsecontentIncluded => this.Value<bool>("cBSEContentIncluded");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("description")]
		public global::System.Web.IHtmlString Description => this.Value<global::System.Web.IHtmlString>("description");

		///<summary>
		/// Description Page Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("descriptionPageContent")]
		public global::System.Web.IHtmlString DescriptionPageContent => this.Value<global::System.Web.IHtmlString>("descriptionPageContent");

		///<summary>
		/// Document and Subscriptions
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("documentAndSubscriptions")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.SubscriptionWiseDocument> DocumentAndSubscriptions => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.SubscriptionWiseDocument>>("documentAndSubscriptions");

		///<summary>
		/// Facebook Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("facebookContent")]
		public string FacebookContent => this.Value<string>("facebookContent");

		///<summary>
		/// Is Active
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("isActive")]
		public bool IsActive => this.Value<bool>("isActive");

		///<summary>
		/// Is Enable for Details Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("isEnableForDetailsPage")]
		public bool IsEnableForDetailsPage => this.Value<bool>("isEnableForDetailsPage");

		///<summary>
		/// Is Guest User Sheet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("isGuestUserSheet")]
		public bool IsGuestUserSheet => this.Value<bool>("isGuestUserSheet");

		///<summary>
		/// Is Quiz Worksheet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("isQuizWorksheet")]
		public bool IsQuizWorksheet => this.Value<bool>("isQuizWorksheet");

		///<summary>
		/// Is Subscription Wise Document
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("isSubscriptionWiseDocument")]
		public bool IsSubscriptionWiseDocument => this.Value<bool>("isSubscriptionWiseDocument");

		///<summary>
		/// Mail Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("mailContent")]
		public string MailContent => this.Value<string>("mailContent");

		///<summary>
		/// Max. Age
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("maxAge")]
		public int MaxAge => this.Value<int>("maxAge");

		///<summary>
		/// Min. Age
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("minAge")]
		public int MinAge => this.Value<int>("minAge");

		///<summary>
		/// Mobile Next-Gen Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("mobileNextGenImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent MobileNextGenImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("mobileNextGenImage");

		///<summary>
		/// Next-Gen Image: Upload here WEBP image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("nextGenImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent NextGenImage => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("nextGenImage");

		///<summary>
		/// Next Year Week for Quiz
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("nextYearWeekForQuiz")]
		public global::Umbraco.Web.Models.Link NextYearWeekForQuiz => this.Value<global::Umbraco.Web.Models.Link>("nextYearWeekForQuiz");

		///<summary>
		/// Offline Post-Quiz Doc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("postQuizDoc")]
		public string PostQuizDoc => this.Value<string>("postQuizDoc");

		///<summary>
		/// Offline Pre-Quiz Doc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("preQuizDoc")]
		public string PreQuizDoc => this.Value<string>("preQuizDoc");

		///<summary>
		/// Previous Year Week for Quiz
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("previousYearWeekForQuiz")]
		public global::Umbraco.Web.Models.Link PreviousYearWeekForQuiz => this.Value<global::Umbraco.Web.Models.Link>("previousYearWeekForQuiz");

		///<summary>
		/// Select Subject
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("selectSubject")]
		public global::Umbraco.Web.Models.Link SelectSubject => this.Value<global::Umbraco.Web.Models.Link>("selectSubject");

		///<summary>
		/// Select Week
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("selectWeek")]
		public global::Umbraco.Web.Models.Link SelectWeek => this.Value<global::Umbraco.Web.Models.Link>("selectWeek");

		///<summary>
		/// Share Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("shareContent")]
		public string ShareContent => this.Value<string>("shareContent");

		///<summary>
		/// Sharing Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("sharingText")]
		public string SharingText => this.Value<string>("sharingText");

		///<summary>
		/// Subscription: Please navigate from Subscription-SubscriptionList folder
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subscription")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> Subscription => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link>>("subscription");

		///<summary>
		/// Sub Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("subTitle")]
		public string SubTitle => this.Value<string>("subTitle");

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("title")]
		public string Title => this.Value<string>("title");

		///<summary>
		/// Select Topic
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("Topic")]
		public global::Umbraco.Web.Models.Link Topic => this.Value<global::Umbraco.Web.Models.Link>("Topic");

		///<summary>
		/// Upgrade Button: Upgrade Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("upgradeButton")]
		public global::Umbraco.Web.Models.Link UpgradeButton => this.Value<global::Umbraco.Web.Models.Link>("upgradeButton");

		///<summary>
		/// Upload Mobile Thumbnail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("uploadMobileThumbnail")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent UploadMobileThumbnail => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("uploadMobileThumbnail");

		///<summary>
		/// Upload PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("uploadPDF")]
		public string UploadPdf => this.Value<string>("uploadPDF");

		///<summary>
		/// Upload Preview PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("uploadPreviewPDF")]
		public string UploadPreviewPdf => this.Value<string>("uploadPreviewPDF");

		///<summary>
		/// Upload Thumbnail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("uploadThumbnail")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent UploadThumbnail => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("uploadThumbnail");

		///<summary>
		/// Use Share Content from here: If checked then content share from here
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("useShareContentFromHere")]
		public bool UseShareContentFromHere => this.Value<bool>("useShareContentFromHere");

		///<summary>
		/// Volume Backgroung CSS: Volume Backgroung CSS
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("volumeBackgroungCSS")]
		public string VolumeBackgroungCss => this.Value<string>("volumeBackgroungCSS");

		///<summary>
		/// WhatsApp Banner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("whatsAppBanner")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent WhatsAppBanner => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("whatsAppBanner");

		///<summary>
		/// WhatsApp Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("whatsAppContent")]
		public string WhatsAppContent => this.Value<string>("whatsAppContent");

		///<summary>
		/// Active On Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("activeOnPage")]
		public bool ActiveOnPage => global::Umbraco.Web.PublishedModels.FooterContent.GetActiveOnPage(this);

		///<summary>
		/// Page Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("pageDesc")]
		public global::System.Web.IHtmlString PageDesc => global::Umbraco.Web.PublishedModels.FooterContent.GetPageDesc(this);

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => global::Umbraco.Web.PublishedModels.FooterContent.GetPageTitle(this);

		///<summary>
		/// Footer FAQs
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("sEOFAQs")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FAqitems> SEofaqs => global::Umbraco.Web.PublishedModels.FooterFaqs.GetSEofaqs(this);

		///<summary>
		/// Show On Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("showOnPage")]
		public bool ShowOnPage => global::Umbraco.Web.PublishedModels.FooterFaqs.GetShowOnPage(this);

		///<summary>
		/// HeadSectionScripts: HeadSectionScripts - *Not Mandatory. The Page Specific code inside the head section goes here:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("headSectionScripts")]
		public string HeadSectionScripts => global::Umbraco.Web.PublishedModels.SEO.GetHeadSectionScripts(this);

		///<summary>
		/// Is Enable for Breadcrumb
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("isEnableForBreadcrumb")]
		public bool IsEnableForBreadcrumb => global::Umbraco.Web.PublishedModels.SEO.GetIsEnableForBreadcrumb(this);

		///<summary>
		/// Meta Description: SEO Meta Description :
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => global::Umbraco.Web.PublishedModels.SEO.GetMetaDescription(this);

		///<summary>
		/// Meta keywords: Meta Keywords:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("metaKeywords")]
		public global::System.Collections.Generic.IEnumerable<string> MetaKeywords => global::Umbraco.Web.PublishedModels.SEO.GetMetaKeywords(this);

		///<summary>
		/// Meta Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("metaName")]
		public string MetaName => global::Umbraco.Web.PublishedModels.SEO.GetMetaName(this);

		///<summary>
		/// Page Title: Browser Title - title shown in the Browser window / tab, and most important on search-engine listings.:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("pageName")]
		public string PageName => global::Umbraco.Web.PublishedModels.SEO.GetPageName(this);

		///<summary>
		/// SEO Can Index: If checked means SEO can track this page, In case of unchecked SEO can not track.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("sEOCanIndex")]
		public bool SEocanIndex => global::Umbraco.Web.PublishedModels.SEO.GetSEocanIndex(this);

		///<summary>
		/// SEO Follow links: SEO Follow links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("sEOFollowLinks")]
		public bool SEofollowLinks => global::Umbraco.Web.PublishedModels.SEO.GetSEofollowLinks(this);
	}
}
