//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.12.2
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Worksheet Root</summary>
	[PublishedModel("worksheetNode")]
	public partial class WorksheetNode : PublishedContentModel, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const string ModelTypeAlias = "worksheetNode";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<WorksheetNode, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public WorksheetNode(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// All Pages Text( Age Wise): All Pages Text( Age Wise)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("allPagesTextAgeWise")]
		public string AllPagesTextAgeWise => this.Value<string>("allPagesTextAgeWise");

		///<summary>
		/// All Pages Text( Category Wise): All Pages Text( Category Wise)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("allPagesTextCategoryWise")]
		public string AllPagesTextCategoryWise => this.Value<string>("allPagesTextCategoryWise");

		///<summary>
		/// All Pages Text( Pathway Wise)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("allPagesTextPathwayWise")]
		public string AllPagesTextPathwayWise => this.Value<string>("allPagesTextPathwayWise");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("description")]
		public global::System.Web.IHtmlString Description => this.Value<global::System.Web.IHtmlString>("description");

		///<summary>
		/// Facebook Content: {worksheeturl},{referal} - required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("facebookContent")]
		public string FacebookContent => this.Value<string>("facebookContent");

		///<summary>
		/// First Time Display Worksheet: Note - Same will be display for all languages - (Listing page)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("firstTimeDisplayWorksheet")]
		public int FirstTimeDisplayWorksheet => this.Value<int>("firstTimeDisplayWorksheet");

		///<summary>
		/// First Time Display Worksheet On Details: Note - Same will be display for all languages - (Details page)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("firstTimeDisplayWorksheetOnDetails")]
		public int FirstTimeDisplayWorksheetOnDetails => this.Value<int>("firstTimeDisplayWorksheetOnDetails");

		///<summary>
		/// Free User Last Week Banner
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("freeUserLastWeekBanner")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent FreeUserLastWeekBanner => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("freeUserLastWeekBanner");

		///<summary>
		/// Mail Content: {worksheeturl},{referal},{loginurl} - required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("mailContent")]
		public string MailContent => this.Value<string>("mailContent");

		///<summary>
		/// Navigation By
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("navigationBy")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FilterOptions> NavigationBy => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FilterOptions>>("navigationBy");

		///<summary>
		/// Navigation Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("navigationTitle")]
		public string NavigationTitle => this.Value<string>("navigationTitle");

		///<summary>
		/// No Of Display Age Groupe for Worksheet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("noOfDisplayAgeGroupeWorksheet")]
		public int NoOfDisplayAgeGroupeWorksheet => this.Value<int>("noOfDisplayAgeGroupeWorksheet");

		///<summary>
		/// Read More
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("readMore")]
		public string ReadMore => this.Value<string>("readMore");

		///<summary>
		/// Referral Content: {referal},{loginurl} - required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("referralContent")]
		public string ReferralContent => this.Value<string>("referralContent");

		///<summary>
		/// See More Media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("seeMoreMedia")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent SeeMoreMedia => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("seeMoreMedia");

		///<summary>
		/// See More Next Gen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("seeMoreNextGen")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent SeeMoreNextGen => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("seeMoreNextGen");

		///<summary>
		/// Social Active: {worksheeturl},{referal},{loginurl} - required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("socialActive")]
		public bool SocialActive => this.Value<bool>("socialActive");

		///<summary>
		/// Start Volume for Referral
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("startVolumeForReferral")]
		public int StartVolumeForReferral => this.Value<int>("startVolumeForReferral");

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("title")]
		public string Title => this.Value<string>("title");

		///<summary>
		/// View All Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("viewAllTitle")]
		public string ViewAllTitle => this.Value<string>("viewAllTitle");

		///<summary>
		/// WhatsApp Banner Default
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("whatsAppBannerDefault")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent WhatsAppBannerDefault => this.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("whatsAppBannerDefault");

		///<summary>
		/// WhatsApp Content: {worksheeturl},{referal},{loginurl} - required
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("whatsAppContent")]
		public string WhatsAppContent => this.Value<string>("whatsAppContent");

		///<summary>
		/// Worksheet Filter Options
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("worksheetFilterOptions")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FilterOptions> WorksheetFilterOptions => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.FilterOptions>>("worksheetFilterOptions");

		///<summary>
		/// HeadSectionScripts: HeadSectionScripts - *Not Mandatory. The Page Specific code inside the head section goes here:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("headSectionScripts")]
		public string HeadSectionScripts => global::Umbraco.Web.PublishedModels.SEO.GetHeadSectionScripts(this);

		///<summary>
		/// Is Enable for Breadcrumb
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("isEnableForBreadcrumb")]
		public bool IsEnableForBreadcrumb => global::Umbraco.Web.PublishedModels.SEO.GetIsEnableForBreadcrumb(this);

		///<summary>
		/// Meta Description: SEO Meta Description :
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => global::Umbraco.Web.PublishedModels.SEO.GetMetaDescription(this);

		///<summary>
		/// Meta keywords: Meta Keywords:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("metaKeywords")]
		public global::System.Collections.Generic.IEnumerable<string> MetaKeywords => global::Umbraco.Web.PublishedModels.SEO.GetMetaKeywords(this);

		///<summary>
		/// Meta Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("metaName")]
		public string MetaName => global::Umbraco.Web.PublishedModels.SEO.GetMetaName(this);

		///<summary>
		/// Page Title: Browser Title - title shown in the Browser window / tab, and most important on search-engine listings.:
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("pageName")]
		public string PageName => global::Umbraco.Web.PublishedModels.SEO.GetPageName(this);

		///<summary>
		/// SEO Can Index: If checked means SEO can track this page, In case of unchecked SEO can not track.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("sEOCanIndex")]
		public bool SEocanIndex => global::Umbraco.Web.PublishedModels.SEO.GetSEocanIndex(this);

		///<summary>
		/// SEO Follow links: SEO Follow links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.12.2")]
		[ImplementPropertyType("sEOFollowLinks")]
		public bool SEofollowLinks => global::Umbraco.Web.PublishedModels.SEO.GetSEofollowLinks(this);
	}
}
